version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mlops_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend:
    image: ghcr.io/yunorga/build_api_ml-main/mlops_backend:latest  # Utilisation de l'image GHCR
    container_name: mlops_backend
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase
      - JWT_SECRET=mysecretkey
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: ghcr.io/yunorga/build_api_ml-main/mlops_frontend:latest  # Utilisation de l'image GHCR
    container_name: mlops_frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    restart: always

volumes:
  db_data:
